version: "3"
services:
    db:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: trainpass
            MYSQL_DATABASE: train071018
        ports:
            - 3307:3306
    app:
        image: golang
        volumes:
            - .:/go/src/train071018
        working_dir: /go/src/train071018/app
        restart: unless-stopped
        depends_on:
                - db
                - migrate
        environment:
            MYSQL_USER: root
            MYSQL_PASS: trainpass
            MYSQL_DB: train071018
            MYSQL_PROTOCOL: tcp
            MYSQL_ADDRESS: db
            MYSQL_PORT: 3307
            APP_PORT: 8080
        ports:
            - 4545:8080
        command: >
            bash -c "go get -d -v ./...
            && go build
            && ./app"
    migrate:
        image: golang
        volumes:
            - .:/go/src/train071018
        working_dir: /go/src/train071018/migrate
        restart: on-failure
        depends_on:
            - db
        environment:
            MYSQL_USER: root
            MYSQL_PASS: trainpass
            MYSQL_DB: train071018
            MYSQL_PROTOCOL: tcp
            MYSQL_ADDRESS: db
            MYSQL_PORT: 3307
        command: >
            bash -c "go get -d -v ./...
            && go build
            && ./migrate"
